apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  ports:
  - name: 8181-8181
    port: 8181
    protocol: TCP
    targetPort: 8181
  selector:
    app: demo
  type: ClusterIP
status:
  loadBalancer: {}
