apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-api
  name: simple-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-api
    spec:
      containers:
      - image: spring/sample-api
        name: simple-api
        imagePullPolicy: Never
        resources: {}

status: {}
