spring:
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
  application:
    name: spring-cloud-integration
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,refresh
