spring:
  application:
    name: qrcode-task
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./shared-folder/database;AUTO_SERVER=TRUE
      username: sa
      password: sa
      driver-class-name: org.h2.Driver
  integration:
    jdbc:
      initialize-schema: always
server:
  port: 9999