# This file is not used any more
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-demo
  name: service-demo
spec:
  ports:
  - name: 8889-8889
    port: 28889
    protocol: TCP
    targetPort: 8889
  selector:
    app: simple-api
  type: ClusterIP
status:
  loadBalancer: {}
