apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          imagePullPolicy: Always
          resources: {}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: abc123
          ports:
            - containerPort: 3306
              name: mysql
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: default
spec:
  ports:
    - nodePort: 30866
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: NodePort
