spring:
  application:
    name: spring-data-jpa
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./shared-folder/database;AUTO_SERVER=TRUE
      username: sa
      password: sa
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true