#spring:
#  application:
#    name: batch-job-application
#  batch:
#    jdbc:
#      initialize-schema: always
#    job:
#      enabled: true # https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/batch/BatchAutoConfiguration.html
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:file:./batchJobs
#      username: sa
#      password: sa
#      driver-class-name: org.h2.Driver
#  main:
#    allow-bean-definition-overriding: true
#logging:
#  level:
#    root: info

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./batchJobs
      username: sa
      password: sa
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: always